[package]
name = "rust-conceptual-project"
version = "0.1.0"
edition = "2021"
authors = ["Gambhir Rathore grathore0110@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
